// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Only run on client-side; skip on server-side to avoid env var issues
    if (typeof window === 'undefined') {
      return next({})
    }

    try {
      const { supabase } = await import('./client')
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch (error) {
      console.error('[Supabase] Auth attachment failed:', error)
      return next({})
    }
  },
)
